name: Deploy Application

on:
  push:
    branches:
      - main # Change this to your main branch if different
  release:
    types: [published] # Trigger on release publication
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Set up Node.js (if applicable)
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '20'  # Specify your Node.js version if applicable

      # - name: Install dependencies (if applicable)
      #   run: |
      #     npm install  # Change this to your package manager if necessary

      - name: Create flat deployable directory
        run: |
          mkdir -p deploy
          find config -type f -exec cp {} deploy/ \;
          find personas -type f -exec cp {} deploy/ \;
          find teams -type f -exec cp {} deploy/ \;
          cp README.md deploy/ || true
          cp USER_GUIDE.md deploy/ || true
          cp Persona_Framework_Implementation_Guide.md deploy/ || true

      - name: Zip deployable directory
        run: |
          cd deploy
          zip -r ../deployable.zip .  # Create a zip file of the deployable directory

      - name: Upload deployable artifact
        uses: actions/upload-artifact@v4
        with:
          name: deployable-artifact
          path: deployable.zip